[package]
version = "0.1.0"
name = "randomx-program"
edition = "2021"

[dependencies]
alloy-sol-types = { workspace = true }
sp1-zkvm = "2.0.0"
unused-lib = { path = "../lib" }
#ccp-randomx = "0.13.3"